Next.js v11 doesn't support exporting i18n routes (read more)
This commit implements a handmade i18n React hook without fancy things that only relies on Next.js's `useRouter` for getting the current locale and default locale.

As a PoC, I made the `DictionaryCard.jsx` presentational component i18n-aware (depending on your strictness, it shouldn't be; it's a PoC, after all). Then I removed/rewrote all the language-related logic from `libs/kobo/dictionaries.js`.

It was working fine. I was happy. Next.js development server worked. And then...

```
Error: i18n support is not compatible with next export. See here for more info on deploying: https://nextjs.org/docs/deployment
    at ~/kobo-offline/node_modules/next/dist/export/index.js:14:322
    at async Span.traceAsyncFn (~/kobo-offline/node_modules/next/dist/telemetry/trace/trace.js:6:584)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kobo-offline@0.1.0 build: `next build && next export`
npm ERR! Exit status 1
[...]
```

For some unknown and, honestly, unexpected reason, Next.js doesn't want to export the site statically. Even when it knows which routes it should render and in which locale it should render them.

I wasn't expecting it to have server-side locale detection, of course. I just wanted my static pages in two different languages, and I was prepared to [pull the trigger on disabling that server-side feature](https://nextjs.org/docs/advanced-features/i18n-routing#disabling-automatic-locale-detection).

I didn't want client-side i18n from the beginning, so I'm left with these options:
- changing the framework to something that doesn't even think about server-side execution; maybe react-static. It doesn't have the notion to i18n routes, but I can build routes for each language, anyway. It's not like I have *quite the number* of routes, to be fair. That would open the door to i18nize each route path also, something that Next.js lacks.
- switching (back?) to Hugo, which is quite fantastic in all what it does (it supports even route paths i18n!), but I'd lose React templating, which is quite unfortunate.
- mangling around some weird environment-based per-language exporting. Non-english exports in a subpath and managing all those bundles. Boo.